services:
  php-mydolar:
    image: midolar-php:latest
    container_name: midolar-php
    ports:
      - "9002:9000"
    volumes:
      - .:/var/www/html
    networks:
      - midolar-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dollarapi
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - midolar-network

  nginx-mydolar:
    image: midolar-nginx:latest
    container_name: midolar-nginx
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php-mydolar
    networks:
      - midolar-network

volumes:
  db_data:

networks:
  midolar-network:
    driver: bridge